name: 'AUR Package Builder using Paru'
description: 'Builds a given AUR package using Paru'
inputs:
  package:
    description: 'The name of the AUR package to build using Paru'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
