name: 'AUR Package Builder using Paru'
description: 'Builds a given AUR package using Paru'
inputs:
  path:
    description: 'Path relative to repo root where PKGBUILD exists'
    required: false
    default: ''
  pre_pkgs:
    description: 'Space separated list of packages to pre install before making the AUR package'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.pre_pkgs }}
